/*Errors*/
export const GET_ERRORS = "GET_ERRORS";
/*Errors*/


/*Board*/
export const GET_PROJECT_BOARDS = "GET_PROJECT_BOARDS";
export const GET_PROJECT_BOARD = "GET_PROJECT_BOARD";
export const DELETE_PROJECT_BOARD = "DELETE_PROJECT_BOARD";
export const PROJECT_BOARD_LOADING = "PROJECT_BOARD_LOADING";
/*Board*/


/*Task*/
export const GET_PROJECT_TASKS = "GET_PROJECT_TASKS";
export const GET_PROJECT_TASK = "GET_PROJECT_TASK";
export const GET_PROJECT_TASK_COUNT = "GET_PROJECT_TASK_COUNT";
export const DELETE_PROJECT_TASK = "DELETE_PROJECT_TASK";
export const PROJECT_TASK_LOADING = "PROJECT_TASK_LOADING";
/*Task*/


/*User*/
export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SECURITY_LOADING = "SECURITY_LOADING";
/*User*/